### ISSUE TITLE
Clicar do gato para a construção não muda o menu

### ISSUE THREAD

**Issue by Jaete** [Jaete/Clawtopia#16]
### BUG
Quando clica-se no gatinho e depois tenta clicar na construção, o gatinho é de-selecionado porém o menu de construtor do gatinho não é substituído pelo menu da construção em si (que possui suas funcionalidades, futuros upgrades e a possibilidade de remoção da mesma). 

Isso ocasiona no gato não estar selecionado no momento em que se tenta construir algo. A construção vai ficar lá, porém precisará mandar o gato manualmente para construí-la em vez de ele ir automaticamente. 

### O que pode ser:
- Dar uma olhada no `Select_units`, dentro do `SimulationMode.cs` pois é este o momento onde os menus são renderizados. Analisar o fluxo e ver onde pode estar o problema.

**Comment by hellvina** [comment]
Testei aqui em main  pelo menos com a construçao principal isto não ocorre mais. @Jaete assim que voce subir o #32 eu testo novamente.

**Comment by Jaete** [comment]
- @hellvina, o #32 foi mergeado. Pode testar novamente, se estiver OK fechamos essa issue, eu acredito que acabei concluindo esse card junto enquanto tentava arrumar o outro.

**Comment by hellvina** [comment]
@Jaete Bug está presente em outras construçoes
